name: Build Windows Binary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile time-check.py
          # Optionally, list the dist folder contents to confirm build
          dir dist

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: time-check-exe
          path: dist\time-check.exe