name: Build and Release Windows Binary

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile time-check.py
          dir dist

      - name: Create GitHub Release and Upload Asset
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
          artifacts: dist/time-check.exe
          generateReleaseNotes: false
          makeLatest: legacy